#!/bin/bash

# Automatic data migration
# With the update from v2.6.4 to v2.6.5, the location of settings and saves changed from
# ~/snap/nxengine-evo/.local/share/nxengine/nxengine-evo/ to
# ~/snap/nxengine-evo/.local/share/nxengine
# Hence, we automatically migrate the data if the old directory exists and the new
# directory doesn't contain any profile*.dat files.
# We do not override profile files if any exist already in the new
# directory.
# Note that settings generated by v2.6.4 are incompatible with v2.6.5, so
# we don't copy them

OLD_DATA_DIR="$SNAP_USER_DATA/.local/share/nxengine/nxengine-evo"
NEW_DATA_DIR="$SNAP_USER_DATA/.local/share/nxengine"

# If the old data dir exists
if [[ -d "$OLD_DATA_DIR" ]]; then
    # If the new data directory doesn't contain any `profile*.dat` files
    if ! compgen -G "$NEW_DATA_DIR/profile"*.dat > /dev/null; then
        # If the old data directory contains any `profile*.dat` files
        if compgen -G "$OLD_DATA_DIR/profile"*.dat > /dev/null; then
            echo "Detected old data folder $OLD_DATA_DIR."
            echo "Copying profile files to $NEW_DATA_DIR."
            cp -n "$OLD_DATA_DIR/profile"*.dat "$NEW_DATA_DIR"
            echo "Data migration complete."
        fi
    fi
fi

exec "$@"

